
export const CHATS_REQUEST = 'CHATS_REQUEST';
export const CHATS_SUCCESS = 'CHATS_SUCCESS';
export const CHATS_FAIL = 'CHATS_FAIL';

export const CHAT_CREATE_REQUEST = 'CHAT_CREATE_REQUEST';
export const CHAT_CREATE_SUCCESS = 'CHAT_CREATE_SUCCESS';
export const CHAT_CREATE_FAIL = 'CHAT_CREATE_FAIL';

export const CHAT_DETAIL_REQUEST = 'CHAT_DETAIL_REQUEST';
export const CHAT_DETAIL_SUCCESS = 'CHAT_DETAIL_SUCCESS';
export const CHAT_UPDATE_CHECK = 'CHAT_UPDATE_CHECK';
export const CHAT_DETAIL_FAIL = 'CHAT_DETAIL_FAIL';

export const CUSTOMER_CHAT = 'CUSTOMER_CHAT';
export const ADMIN_RESPONSE = 'ADMIN_RESPONSE';