
export const STORES_REQUEST = 'STORES_REQUEST';
export const STORES_SUCCESS = 'STORES_SUCCESS';
export const STORES_FAIL = 'STORES_FAIL';

export const STORE_CREATE_REQUEST = 'STORE_CREATE_REQUEST';
export const STORE_CREATE_SUCCESS = 'STORE_CREATE_SUCCESS';
export const STORE_CREATE_FAIL = 'STORE_CREATE_FAIL';

export const STORE_UPDATE_REQUEST = 'STORE_UPDATE_REQUEST';
export const STORE_UPDATE_SUCCESS = 'STORE_UPDATE_SUCCESS';
export const STORE_UPDATE_FAIL = 'STORE_UPDATE_FAIL';

export const STORE_DETAIL_REQUEST = 'STORE_DETAIL_REQUEST';
export const STORE_DETAIL_SUCCESS = 'STORE_DETAIL_SUCCESS';
export const STORE_DETAIL_FAIL = 'STORE_DETAIL_FAIL';